import time
from random import randint
from pypresence import Presence
import requests_futures.sessions
from requests_futures.sessions import FuturesSession

print("Thank you for downloading Veritify's Tool!")
print()
print()
time.sleep(2)
print("[~]  How to use:")
time.sleep(3)
print("[~]  Go into 'config.json' and input your discord token.")
time.sleep(4)
print("[~]  Enter the ID of the server into the 'guild-id' line in 'config.json'")
time.sleep(5)
print("[~]  Enter the channel ID into 'channelspamid' in 'config.json'")
time.sleep(4)
print("[~]  Enter the message you want spammed into'spam_message' in 'config.json'")
time.sleep(4)
print("[~]  Enter the name of the role you want created into 'rolespam' in 'config.json'")
time.sleep(4)
print("[~]  Enter then name of the channel you want spammed into 'channelspam' in 'config.json'")
time.sleep(4)
print("[~]  Then simply just run the 'run.bat' file and the tool will pop up!")
time.sleep(2)
print("[~]  When you open 'run.bat', all the 'config.json' settings will pop up!")
print()
print()
time.sleep(3)
print("[~]  Thank you for using Veritify's tool.")
time.sleep(2)
print("[~]  If there are any issues please dm: Veritify#0001")
time.sleep(1)
print()
print()
print()
print()
print("[~]  Close this tab after read.")
time.sleep(900)